modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "immersiveposres"
version = "${version}"
displayName = "Immersive positional resources"
displayURL = "https://dreaming.codes"
authors = "DreamingCodes"
description = "Change Immersive virtual ore veins based on distance from spawn"

[[dependencies.immersiveposres]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.immersiveposres]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${mc_version}]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.immersiveposres]]
    modId = "immersiveengineering"
    mandatory = true
    versionRange = "[${immersive_version},)"
    ordering = "AFTER"
    side = "BOTH"